#!/usr/bin/env bash
# Display listening ports and associated programs on the machine
#+ That only shows listening sockets
#+ That shows the PID and name of the program to which each socket belongs

netstat -l --program
